apiVersion: v1
kind: Pod
metadata:
  name: aceoperatordb
  labels:
    author: quik-computing
    app: aceoperatordb
spec:
  restartPolicy: Never
  containers:
  - name: ace-db
    image: mariadb:5.5.52
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: aceoperator
            key: mysql_root_password
