apiVersion: v1
kind: Pod
metadata:
  name: aceoperator
  namespace: aceoperator
  labels:
    installation: aceoperator
spec:
  containers:
  - name: ace-db
    image: mariadb:5.5.52
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: aceoperator-secrets
            key: root_password
  restartPolicy: Never