kind: Service
apiVersion: v1
metadata:
  name: aceoperator
spec:
  selector:
    app: aceoperator
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    nodePort: 30443