apiVersion: v1
kind: Pod
metadata:
  name: webtalk
  labels:
    author: quik-computing
    app: aceoperator
    instance: webtalk
spec:
  restartPolicy: Never
  containers:
  - name: ace-data
    image: "quik/aceoperator-data:3.1.0-SNAPSHOT"
    volumeMounts:
      - mountPath: /var/aceoperator
        name: aceoperator-home
    env:
      - name: ACEOPERATOR_SQL_HOST
        value: "aceoperatordb.aceoperator.svc.cluster.local"
      - name: ACEOPERATOR_SQL_PORT
        value: "3306"
      - name: ACEOPERATOR_SQL_DB
        value: "webtalk"
      - name: ACEOPERATOR_SQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: aceoperator
            key: mysql_root_password
      - name: ACEOPERATOR_SQL_USER
        value: ace
      - name: ACEOPERATOR_SQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: webtalk
            key: mysql_ace_password
      - name: ACEOPERATOR_SMTP_SERVER
        value: 127.0.0.1
      - name: ACEOPERATOR_SMTP_USER
        value: ""
      - name: ACEOPERATOR_SMTP_PASSWORD
        value: ""
      - name: LOAD_DEMO
        value: "true"
      - name: RUN_SEED
        value: "true"
  - name: ace-app
    image: "quik/aceoperator-app:3.1.0-SNAPSHOT"
    env:
      - name: ACEOPERATOR_DATA_HOST
        value: 127.0.0.1
    volumeMounts:
      - mountPath: /var/aceoperator
        name: aceoperator-home
  volumes:
    - name: aceoperator-home
      emptyDir: {}