use mysql;

GRANT ALL PRIVILEGES ON webtalk.* TO $$ACE(ACEOPERATOR_SQL_USER)@localhost IDENTIFIED BY '$$ACE(ACEOPERATOR_SQL_PASSWORD)';
GRANT ALL PRIVILEGES ON webtalk.* TO $$ACE(ACEOPERATOR_SQL_USER)@localhost.localdomain IDENTIFIED BY '$$ACE(ACEOPERATOR_SQL_PASSWORD)';
GRANT ALL PRIVILEGES ON webtalk.* TO $$ACE(ACEOPERATOR_SQL_USER)@'%' IDENTIFIED BY '$$ACE(ACEOPERATOR_SQL_PASSWORD)';

CREATE DATABASE webtalk;