CREATE TABLE form_tbl (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  session VARCHAR(255) binary NOT NULL,
  canned_msg_id BIGINT UNSIGNED NOT NULL,
  send_time TIMESTAMP NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  
  INDEX(send_time)
) ENGINE = InnoDB;