apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webtalk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aceoperator
        instance: webtalk
    spec:
      initContainers:
      - name: ace-data
        image: "quik/aceoperator-data:3.1.0-SNAPSHOT"
        volumeMounts:
          - mountPath: /var/aceoperator
            name: aceoperator
            subPath: instance/webtalk
        env:
          - name: ACE3_DATA_EXIT
            value: "true"
          - name: ACEOPERATOR_SQL_HOST
            value: "aceoperatordb.aceoperator.svc.cluster.local"
          - name: ACEOPERATOR_SQL_PORT
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: db.port
          - name: ACEOPERATOR_SQL_DB
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['instance']
          - name: ACEOPERATOR_SQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aceoperator
                key: mysql_root_password
          - name: ACEOPERATOR_SQL_USER
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['instance']
          - name: ACEOPERATOR_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webtalk
                key: mysql_ace_password
          - name: ACEOPERATOR_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webtalk
                key: admin_password
          - name: ACE3_DATA_RUN_SEED
            valueFrom:
              configMapKeyRef:
                name: webtalk
                key: data.runSeed
          - name: ACE3_DATA_RUN_PATCH
            valueFrom:
              configMapKeyRef:
                name: webtalk
                key: data.runPatch
          - name: ACE3_DATA_LOAD_USERS
            valueFrom:
              configMapKeyRef:
                name: webtalk
                key: data.loadUsers
          - name: ACE3_DATA_USERS
            valueFrom:
              secretKeyRef:
                name: webtalk
                key: data_operators
          - name: ACE3_DATA_EMAIL_TRANSCRIPT
            valueFrom:
              configMapKeyRef:
                name: webtalk
                key: data.sendTranscript
      containers:
      - name: ace-app
        image: "quik/aceoperator-app:3.1.0-SNAPSHOT"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
          - name: ACE3_APP_CNT_SYNC
            value: "false"
          - name: ACE3_APP_DATA_HOST
            value: 127.0.0.1
          - name: ACEOPERATOR_SQL_HOST
            value: "aceoperatordb.aceoperator.svc.cluster.local"
          - name: ACEOPERATOR_SQL_PORT
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: db.port
          - name: ACEOPERATOR_SQL_DB
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['instance']
          - name: ACEOPERATOR_SQL_USER
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['instance']
          - name: ACEOPERATOR_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webtalk
                key: mysql_ace_password
          - name: ACEOPERATOR_SMTP_SERVER
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: data.smtpServer
          - name: ACEOPERATOR_SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: data.smtpPort
          - name: ACEOPERATOR_SMTP_USER
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: data.smtpUser
          - name: ACEOPERATOR_SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aceoperator
                key: smtp_password
          - name: ACEOPERATOR_MAIL_ENCRYPT
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: data.mailEncrypt
          - name: ACEOPERATOR_MAIL_OVERRIDE_FROM
            valueFrom:
              configMapKeyRef:
                name: aceoperator
                key: data.mailOverrideFrom
          - name: ACEOPERATOR_RECAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: aceoperator
                key: recaptcha_secret
        volumeMounts:
          - mountPath: /var/aceoperator
            name: aceoperator
            subPath: instance/webtalk
      securityContext:
        fsGroup: 1000
      volumes:
      - name: aceoperator
        persistentVolumeClaim:
          claimName: aceoperator