version: "2"
services:
    app:
        container_name: ace-app
        image: "quik/aceoperator-app:${project.version}"
        links:
          - "db:${ACEOPERATOR_SQL_HOST}"
          - "mail:${ACEOPERATOR_SMTP_SERVER}"
        networks:
          - "network"
        environment:
          - "ACE3_APP_DATA_HOST=${ACE3_APP_DATA_HOST}"

          - "ACEOPERATOR_SQL_HOST=${ACEOPERATOR_SQL_HOST}"
          - "ACEOPERATOR_SQL_PORT=${ACEOPERATOR_SQL_PORT}"
          - "ACEOPERATOR_SQL_DB=${ACEOPERATOR_SQL_DB}"
          - "ACEOPERATOR_SQL_USER=${ACEOPERATOR_SQL_USER}"
          - "ACEOPERATOR_SQL_PASSWORD=${ACEOPERATOR_SQL_PASSWORD}"

          - "ACEOPERATOR_SMTP_SERVER=${ACEOPERATOR_SMTP_SERVER}"
          - "ACEOPERATOR_SMTP_PORT=${ACEOPERATOR_SMTP_PORT}"
          - "ACEOPERATOR_SMTP_USER=${ACEOPERATOR_SMTP_USER}"
          - "ACEOPERATOR_SMTP_PASSWORD=${ACEOPERATOR_SMTP_PASSWORD}"
          - "ACEOPERATOR_MAIL_ENCRYPT=${ACEOPERATOR_MAIL_ENCRYPT}"
          - "ACEOPERATOR_MAIL_OVERRIDE_FROM=${ACEOPERATOR_MAIL_OVERRIDE_FROM}"
          - "ACEOPERATOR_RECAPTCHA_SECRET=${ACEOPERATOR_RECAPTCHA_SECRET}"

          - "ACE3_APP_CNT_SYNC=true"
        volumes:
          - "${ACEOPERATOR_HOME}:/var/aceoperator"
    frontend:
        container_name: ace-frontend
        image: "quik/aceoperator-frontend:${project.version}"
        ports:
          - "80:80"
          - "443:443"
        links:
          - "app:${ACE3_FE_APP_HOST}"
        networks:
          - "network"
        environment:
          - "ACE3_FE_APP_HOST=${ACE3_FE_APP_HOST}" 
          - "ACE3_FE_CERTS_DIR=${ACE3_FE_CERTS_DIR}"
        volumes:
          - "${ACE3_FE_CERTS_DIR}:/etc/ssl/certs"
networks:
  network:
    driver: bridge
volumes:
  acedb: