version: "2"
services:
    db:
        container_name: ace-db
        image: "mariadb:5.5.52"
        ports: 
          - "3306:3306"
        volumes:
          - "acedb:/var/lib/mysql"
        networks:
          - "network"
        environment:
          - "MYSQL_ROOT_PASSWORD=${ACEOPERATOR_SQL_ROOT_PASSWORD}"
networks:
  network:
    driver: bridge
volumes:
  acedb: